kind: Secret
apiVersion: v1
metadata:
  name: kube-config-secret
  namespace: default
  uid: 0e5f4f6c-3b7d-47f2-9fbb-63692075f57e
  resourceVersion: '898073'
  creationTimestamp: '2021-10-26T09:12:49Z'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2021-10-26T09:12:49Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:myscpassword: {}
          f:myscusername: {}
        f:type: {}
data:
  myscpassword: bXlwYXNzd29yZA==
  myscusername: bXl1c2VybmFtZQ==
type: Opaque
